# Generated by Django 4.2.15 on 2024-08-29 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField(blank=True)),
                ('date_of_death', models.DateField(blank=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('country_of_birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators_born', to='viewer.country')),
                ('country_of_death', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators_died', to='viewer.country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_orig', models.CharField(max_length=150)),
                ('title_cz', models.CharField(max_length=150)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='acting', to='viewer.creator')),
                ('countries', models.ManyToManyField(blank=True, related_name='movies', to='viewer.country')),
                ('director', models.ManyToManyField(blank=True, related_name='directing', to='viewer.creator')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='viewer.genre')),
            ],
        ),
    ]
