# Generated by Django 4.2.15 on 2024-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
