# Generated by Django 4.2.15 on 2024-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
