# Generated by Django 4.2.15 on 2024-09-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_creator_date_of_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterField(
            model_name='creator',
            name='country_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators_born', to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='country_of_death',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators_died', to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='surname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
