# Generated by Django 4.2.15 on 2024-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_creator_options_alter_creator_country_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
