# Generated by Django 4.2.15 on 2024-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_creator_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='released',
        ),
        migrations.AddField(
            model_name='movie',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
